platform :macos, '10.10'
inhibit_all_warnings!

target 'GithubPulse' do

  pod 'IYLoginItem'
  pod 'INPopoverController', git: 'https://github.com/indragiek/INPopoverController.git'
  pod 'SSZipArchive'
  pod 'EDSemver'

end
