# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GithubPulse' do

pod 'IYLoginItem', git: 'https://github.com/ianyh/IYLoginItem.git'
pod 'INPopoverController', git: 'https://github.com/indragiek/INPopoverController.git'

end

